const Diet = [
    { id: 1, diet: "Vegetarian" },
    { id: 2, diet: "Vegan" },
    { id: 3, diet: "Pescatarian" },
    { id: 4, diet: "Non-Vegetarian" },
    { id: 5, diet: "Gluten-Free" },
    { id: 6, diet: "Keto" },
    { id: 7, diet: "Paleo" },
    { id: 8, diet: "Low-Carb" },
    { id: 9, diet: "Mediterranean" },
    { id: 10, diet: "Intermittent Fasting" },
    { id: 11, diet: "DASH Diet" },
    { id: 12, diet: "Flexitarian" },
    { id: 13, diet: "Raw Food Diet" },
    { id: 14, diet: "Atkins Diet" },
    { id: 15, diet: "South Beach Diet" },
    { id: 16, diet: "Whole30" },
    { id: 17, diet: "Zone Diet" },
    { id: 18, diet: "Nordic Diet" },
    { id: 19, diet: "Macrobiotic Diet" },
    { id: 20, diet: "Volumetrics Diet" },
    { id: 21, diet: "Jenny Craig" },
    { id: 22, diet: "Nutrisystem" },
    { id: 23, diet: "Weight Watchers" },
    { id: 24, diet: "Ornish Diet" },
    { id: 25, diet: "Mayo Clinic Diet" },
    { id: 26, diet: "MIND Diet" },
    { id: 27, diet: "Fertility Diet" },
    { id: 28, diet: "Anti-Inflammatory Diet" },
    { id: 29, diet: "Alkaline Diet" },
    { id: 30, diet: "HCG Diet" },
];

export default Diet